CREATE DATABASE IF NOT EXISTS base;


CREATE TABLE IF NOT EXISTS 'base'.'tb_nova' (
        Campo1 TEXT,
        Campo2 TEXT,
        Campo3 TEXT,
        Campo4 TEXT,
        Campo5 TEXT,
        Campo6 TEXT,
        Campo7 TEXT,
        Campo8 TEXT,
        Campo9 TEXT,
        Campo10 TEXT,
        Campo11 TEXT,
        Campo12 TEXT,
        Campo13 TEXT,
        Campo14 TEXT,
        Campo15 TEXT,
        Campo16 TEXT,
        Campo17 TEXT,
        Campo18 TEXT,
        Campo19 TEXT,
        Campo20 TEXT,
        Campo21 TEXT,
        Campo22 TEXT,
        Campo23 TEXT,
        Campo24 TEXT,
        Campo25 TEXT,
        Campo26 TEXT,
        Campo27 TEXT,
        Campo28 TEXT,
        Campo29 TEXT,
        Campo30 TEXT,
        Campo31 TEXT,
        Campo32 TEXT,
        Campo33 TEXT,
        Campo34 TEXT,
        Campo35 TEXT,
        Campo36 TEXT,
        Campo37 TEXT,
        Campo38 TEXT,
        Campo39 TEXT,
        Campo40 TEXT
    );


CREATE TABLE IF NOT EXISTS 'base'.'tb_referencia' (
        Campo1 TEXT,
        Campo2 TEXT,
        Campo3 TEXT,
        Campo4 TEXT,
        Campo5 TEXT,
        Campo6 TEXT,
        Campo7 TEXT,
        Campo8 TEXT,
        Campo9 TEXT,
        Campo10 TEXT,
        Campo11 TEXT,
        Campo12 TEXT,
        Campo13 TEXT,
        Campo14 TEXT,
        Campo15 TEXT,
        Campo16 TEXT,
        Campo17 TEXT,
        Campo18 TEXT,
        Campo19 TEXT,
        Campo20 TEXT,
        Campo21 TEXT,
        Campo22 TEXT,
        Campo23 TEXT,
        Campo24 TEXT,
        Campo25 TEXT,
        Campo26 TEXT,
        Campo27 TEXT,
        Campo28 TEXT,
        Campo29 TEXT,
        Campo30 TEXT,
        Campo31 TEXT,
        Campo32 TEXT,
        Campo33 TEXT,
        Campo34 TEXT,
        Campo35 TEXT,
        Campo36 TEXT,
        Campo37 TEXT,
        Campo38 TEXT,
        Campo39 TEXT,
        Campo40 TEXT
    );

    CREATE TABLE IF NOT EXISTS 'base'.'tb_analise' (
        Campo1 TEXT,
        Campo2 TEXT,
        Campo3 TEXT,
        Campo4 TEXT,
        Campo5 TEXT,
        Campo6 TEXT,
        Campo7 TEXT,
        Campo8 TEXT,
        Campo9 TEXT,
        Campo10 TEXT
        );

